name: Build STM32C5

on:
  push:
    paths:
      - 'apps/**'
      - 'cmake/**'
      - 'lib/**'
      - 'ports/family_support.cmake'
      - 'ports/stm32c5/**'
      - 'src/**'
      - '.github/actions/**'
      - '.github/workflows/build.yml'
      - '.github/workflows/build_util.yml'
  pull_request:
    branches: [ master ]
    paths:
      - 'apps/**'
      - 'cmake/**'
      - 'lib/**'
      - 'ports/family_support.cmake'
      - 'ports/stm32c5/**'
      - 'src/**'
      - '.github/actions/**'
      - '.github/workflows/build.yml'
      - '.github/workflows/build_util.yml'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  c5-bootloader:
    uses: ./.github/workflows/build_util.yml
    with:
      port: 'stm32c5'
      boards: '["xiao_c5"]'
      build-system: 'cmake'
      toolchain: 'arm-gcc'
